import pygame

#CONSTANTRS.PY HOLDS ALL THE CONSTANTS USED IN GAME... SHOULD NOT BE CHANGED IN CODE


SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_HEALTH = 100

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

POWER_UP_RADIUS = 30


PHAZER_RADIUS = 20
PHAZER_TURN_SPEED = 300
PHAZER_SPEED = 200
PHAZER_HEALTH = 100
PHAZER_SHOT_RADIUS = 5
PHAZER_SHOOT_SPEED = 500
PHAZER_SHOOT_COOLDOWN = 0.3
PHAZER_GUN1_DAMAGE = 50





SOROB_RADIUS = 20
SOROB_TURN_SPEED = 30
SOROB_SPEED = 200
SOROB_HEALTH = 1000
SOROB_SHOT_RADIUS = 5
SOROB_SHOOT_SPEED = 500
SOROB_SHOOT_COOLDOWN = 1.0
SOROB_GUN1_DAMAGE = 50

